packages:
  - 'apps/*'
  - 'packages/*'

# Catalog configuration for better dependency management
catalog:
  react: ^18.2.0
  react-dom: ^18.2.0
  next: ^14.0.0
  typescript: ^5.0.0
  tailwindcss: ^3.3.0
  prisma: ^5.0.0
  express: ^4.18.0
  axios: ^1.6.0
  zod: ^3.22.0
