name = "hdbank-backend"
main = "src/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Worker configuration
[env.production]
name = "hdbank-backend-prod"
vars = { ENVIRONMENT = "production" }

[[env.production.durable_objects.bindings]]
name = "USER_PROFILE_DO"
class_name = "UserProfileDO"
script_name = "hdbank-backend-prod"

[[env.production.durable_objects.bindings]]
name = "FAMILY_DO"
class_name = "FamilyDO"
script_name = "hdbank-backend-prod"

[[env.production.durable_objects.bindings]]
name = "COMMUNITY_WALLET_DO"
class_name = "CommunityWalletDO"
script_name = "hdbank-backend-prod"

[[env.production.durable_objects.bindings]]
name = "SMART_REWARDS_DO"
class_name = "SmartRewardsDO"
script_name = "hdbank-backend-prod"

[env.staging]
name = "hdbank-backend-staging"
vars = { ENVIRONMENT = "staging" }

[[env.staging.durable_objects.bindings]]
name = "USER_PROFILE_DO"
class_name = "UserProfileDO"
script_name = "hdbank-backend-staging"

[[env.staging.durable_objects.bindings]]
name = "FAMILY_DO"
class_name = "FamilyDO"
script_name = "hdbank-backend-staging"

[[env.staging.durable_objects.bindings]]
name = "COMMUNITY_WALLET_DO"
class_name = "CommunityWalletDO"
script_name = "hdbank-backend-staging"

[[env.staging.durable_objects.bindings]]
name = "SMART_REWARDS_DO"
class_name = "SmartRewardsDO"
script_name = "hdbank-backend-staging"

# Durable Objects
[[durable_objects.bindings]]
name = "USER_PROFILE_DO"
class_name = "UserProfileDO"

[[durable_objects.bindings]]
name = "FAMILY_DO"
class_name = "FamilyDO"

[[durable_objects.bindings]]
name = "COMMUNITY_WALLET_DO"
class_name = "CommunityWalletDO"

[[durable_objects.bindings]]
name = "SMART_REWARDS_DO"
class_name = "SmartRewardsDO"

# Durable Object Migrations
[[migrations]]
tag = "v1"
new_sqlite_classes = ["UserProfileDO"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["FamilyDO", "CommunityWalletDO", "SmartRewardsDO"]

# KV Namespaces for caching
[[kv_namespaces]]
binding = "CACHE"
id = "2d43ed1a5ba243b592bfe21bd4a12b49"
preview_id = "your-preview-kv-namespace-id"

# D1 Database (if using Cloudflare D1 instead of external PostgreSQL)
# [[d1_databases]]
# binding = "DB"
# database_name = "hdbank-db"
# database_id = "your-d1-database-id"

# Environment variables (use wrangler secret for sensitive data)
[vars]
NODE_ENV = "development"
CORS_ORIGIN = "https://22140156.locuno-hdbank-frontend.pages.dev"
JWT_SECRET = "your-super-secret-jwt-key-change-this-in-production"
JWT_EXPIRES_IN = "24h"
BCRYPT_ROUNDS = "12"
RATE_LIMIT_WINDOW_MS = "900000"
RATE_LIMIT_MAX_REQUESTS = "100"

# Build configuration - let wrangler handle TypeScript compilation
# [build]
# command = "pnpm run build"

# Limits - removed for free plan compatibility
# [limits]
# cpu_ms = 50000
