name = "hdbank-backend"
main = "src/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Worker configuration
[env.production]
name = "hdbank-backend-prod"
vars = { ENVIRONMENT = "production" }

[env.staging]
name = "hdbank-backend-staging"
vars = { ENVIRONMENT = "staging" }

# KV Namespaces for caching
[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

# D1 Database (if using Cloudflare D1 instead of external PostgreSQL)
# [[d1_databases]]
# binding = "DB"
# database_name = "hdbank-db"
# database_id = "your-d1-database-id"

# Environment variables (use wrangler secret for sensitive data)
[vars]
NODE_ENV = "development"
CORS_ORIGIN = "https://hdbank.pages.dev"
JWT_EXPIRES_IN = "24h"
BCRYPT_ROUNDS = "12"
RATE_LIMIT_WINDOW_MS = "900000"
RATE_LIMIT_MAX_REQUESTS = "100"

# Build configuration - let wrangler handle TypeScript compilation
# [build]
# command = "pnpm run build"

# Limits - removed for free plan compatibility
# [limits]
# cpu_ms = 50000
